### ISSUE TITLE
Crash if eslint and stylelint config are not set in .dist file

### ISSUE THREAD

**Issue by gorkalaucirica** [LIN3S/CS#5]
The following yml crashes when been used as .dist:

```yaml

parameters:
    enabled:
        - phpmd
        - phpcsfixer

    name: Php DDD Standard
    type: project
    year: 2017
    author: LIN3S
    email: info@lin3s.com
    version: 0.1

    phpmd_path: src
    phpmd_rules:
        - controversial
        - unusedcode
        - codesize
        - naming

    phpcsfixer_path: src
    phpcsfixer_test_path: tests
    phpcsfixer_file_location: vendor/lin3s/cs/src/LIN3S/CS/
```
