### ISSUE TITLE
PhpCSFixer does not work

### ISSUE THREAD

**Issue by gorkalaucirica** [LIN3S/CS#6]
Version: 0.7.x

Steps to reproduce in a clean PHP project:

- `composer req lin3s/cs --dev`
- Copy composer.json required `scripts` and `extra` sections
- Use following config (as detailed in docs):
```yaml
parameters:
    enabled:
        - phpmd
        - phpcsfixer
    name: Issue 
    type: project
    year: 2017
    author: LIN3S
    email: info@lin3s.com
    version: 0.1
    phpmd_path: src
    phpmd_rules:
        - controversial
        - unusedcode
        - codesize
        - naming
    twigcs_path: src
    phpcsfixer_path: src
    phpcsfixer_test_path: tests
    phpcsfixer_file_location: vendor/lin3s/cs/src/LIN3S/CS/
```
* Disable null output in `LIN3S\CS\Checker\PhpCsFixer`
* Commit src folder

You get the following error:

`The "<path-to-project>/vendor/lin3s/cs/src/LIN3S/CS/src" directory does not exist.`

**Comment by gorkalaucirica** [comment]
This can be fixed with the following config (note `phpcsfixer_file_location`):

```
# This file is auto-generated during the composer install
parameters:
    enabled:
        - phpmd
        - twigcs
        - phpcsfixer
    name: 'Aldi IMA'
    type: project
    year: '2018 - present'
    author: LIN3S
    email: info@lin3s.com
    version: 0.1
    phpmd_path: src
    phpmd_rules:
        - controversial
        - unusedcode
        - codesize
        - naming
    twigcs_path: templates
    phpcsfixer_path: src
    phpcsfixer_test_path: tests
    phpcsfixer_file_location: ''
```
